import type { Project } from '$lib/model/Project';
import { beatBox, foolsball, piano } from '$lib/content/blogPosts';
import { asset, resolve } from '$app/paths';

export const projects: Project[] = [
  {
    id: 'ludiek',
    title: 'Ludiek',
    description: 'The game engine that focuses on the fun. A data-driven successor of the Incremental Game Template',
    date: '2026-present',
    image: asset('/images/ludiek.png'),
    url: 'https://ludiek.123ishatest.com',
  },
  {
    id: 'lands-unknown',
    title: 'Lands Unknown',
    description: 'Lands Unknown is a fantasy ludiverse spanning across various games',
    date: '2026-present',
    image: asset('/images/lands-unknown.png'),
    url: 'https://lands-unknown.com',
  },
  {
    id: 'the-road-not-taken',
    title: 'The Road Not Taken',
    description: 'An exploration incremental game created for the Big Mode Game Jam 2025',
    date: '2025',
    image: asset('/images/road-not-taken.png'),
    url: 'https://123ishatest.itch.io/the-road-not-taken',
  },
  {
    ...foolsball,
    url: resolve(foolsball.path),
    image: asset('/images/foosball.png'),
    date: '2024',
  },
  {
    ...beatBox,
    url: resolve(beatBox.path),
    image: asset('/images/beatbox/beatbox-led.jpg'),
    date: '2024',
  },
  {
    ...piano,
    url: resolve(piano.path),
    // TODO(@Isha): Change to mario photo
    image: asset('/images/pianos/piano-open.png'),
    date: '2023',
  },
  {
    id: 'incremental-game-template',
    title: 'Incremental Game Template!',
    description: 'A collection of useful scripts to help you develop incremental games',
    date: '2022',
    image: asset('/images/incremental-game-template.png'),
    url: 'https://123ishatest.github.io/igt-docs',
  },
  {
    id: 'stable-jewels',
    title: 'Stable Jewels',
    description: 'A silly incremental game prototype that turned out quite fun!',
    date: '2021',
    image: asset('/images/stable-jewels.png'),
    url: 'https://123ishatest.github.io/stable-jewels',
  },
  {
    id: 'card-quest',
    title: 'Card Quest',
    description: 'A Deck-building incremental game created for the r/incremental_games 2021 jam!',
    date: '2021',
    image: asset('/images/card-quest.png'),
    url: 'https://ishad.itch.io/card-quest',
  },
  {
    id: 'gamehop',
    title: 'Gamehop',
    description: 'An attention divider incremental made for 2020 r/incremental_games jam!',
    date: '2020',
    image: asset('/images/gamehop.png'),
    url: 'https://ishadijcks.github.io/incremental-games-2020-jam',
  },
  {
    id: 'timehop',
    title: 'Timehop',
    description: 'A time travel incremental made for Ludum Dare 47',
    date: '2020',
    image: asset('/images/timehop.png'),
    url: 'https://ldjam.com/events/ludum-dare/47/timehop',
  },
  {
    id: 'project-march',
    title: 'Project March',
    description: 'Building robotic legs so that paraplegic patients can walk again',
    date: '2019',
    image: asset('/images/project-march.png'),
    url: 'https://www.projectmarch.nl/',
  },
  {
    id: 'pokeclicker',
    title: 'PokéClicker',
    description: 'A pokemon-inspired incremental game where you become the very best (like no one ever was)',
    date: '2015',
    image: asset('/images/pokeclicker.png'),
    url: 'https://pokeclicker.com',
  },
];
